Repository pomerium/documentation, pull requests merged in 2023-01, with the labels that each got.

#245 docs: complete v0.20 chores
  content/docs/releases/enterprise/changelog.mdx
  content/docs/releases/enterprise/upgrading.mdx
Labels: backport 0-20-0

#251 update changelog.mdx to include v0.20
  content/docs/releases/changelog.mdx
Labels: backport 0-20-0

#271 update codec_type
  content/docs/reference/codec-type.md
Labels: backport 0-20-0

#264 Docs: adds js sdk guide for Core and Enterprise
  content/docs/guides/img/js-sdk/js-sdk-enterprise-policy.png
  content/docs/guides/img/js-sdk/js-sdk-enterprise-route.png
  content/docs/guides/img/js-sdk/js-sdk-jwt-error.png
  content/docs/guides/img/js-sdk/js-sdk-jwt-payload.png
  content/docs/guides/img/js-sdk/js-sdk-react-app-browser.png
  content/docs/guides/js-sdk.mdx
  content/examples/js-sdk/express-server.md
  content/examples/js-sdk/react-app.md
Labels: backport 0-20-0

#290 Docs: Fixes 404ing links
  static/_redirects
Labels: docs, backport 0-20-0

#303 cspell: ignore k8s folder
  cspell.json
Labels: backport 0-20-0

#270 Docs: adds TCP reference for pomerium-cli
  content/docs/capabilities/tcp/reference/tcp-cli-reference.md
  k8s/config-template/ingress-console.yaml
  k8s/console/deployment/args.yaml
Labels: backport 0-20-0

#315 update-k8s-reference-3e5c08d6fccac64c08bac6871f0a6b800ada6f6c
  content/docs/deploying/k8s/reference.md
Labels: backport 0-20-0

#317 Docs: adds JS SDK capabilities page
  content/docs/capabilities/jwt-verification.mdx
  sidebars.js
Labels: backport 0-20-0

#342 use git references in kubectl apply -k commands
  content/docs/deploying/k8s/install.md
  content/docs/deploying/k8s/quickstart.mdx
  content/docs/releases/enterprise/install/kustomize.mdx
  package.json
  static/k8s/console.yaml
  static/k8s/core.yaml
Labels: backport 0-20-0

#344 Docs: adds pomerium-enterprise namespace to kustomization.yaml
  k8s/config-template/kustomization.yaml
Labels: backport 0-20-0

#353 Update enterprise.md
  content/docs/releases/enterprise/install/enterprise.md
Labels: backport 0-20-0

#355 use git refs in kustomize command
  content/docs/releases/enterprise/install/kustomize.mdx
  k8s/core/kustomization.yaml
  k8s/core/service.yaml
  static/k8s/console.yaml
  static/k8s/core.yaml
Labels: bug
