Repository pomerium/documentation, pull requests merged in 2023-02, with the labels that each got.

#349 Docs: updates Docker Compose quickstart
  content/docs/quickstart.mdx
  content/examples/config/config.docker.yaml.md
  content/examples/docker/basic.docker-compose.yml.md
Labels: backport 0-20-0

#373 Docs: fixes error message header typos and MD link
  content/docs/reference/branding/error-message-first-paragraph.md
Labels: backport 0-20-0

#372 Docs: updates access control docs
  content/docs/concepts/access-control.mdx
Labels: backport 0-20-0

#381 Docs: updates enterprise install text and k8s links
  content/docs/releases/enterprise/install/enterprise.md
Labels: backport 0-20-0

#384 Docs: updates core docker quickstart signing key and verify screenshot
  content/docs/img/quickstart/jwt-claims.png
  content/docs/img/quickstart/pomerium-proceed-to-verify.png
  content/docs/quickstart.mdx
  content/examples/config/config.docker.yaml.md
  content/examples/docker/basic.docker-compose.yml.md
Labels: backport 0-20-0

#379 Linking Docs and Blogs
  content/docs/concepts/zero-trust.md
Labels: backport 0-20-0

#378 Linking blog/doc
  content/docs/index.mdx
Labels: backport 0-20-0

#386 Docs: updates authn capabilities doc
  content/docs/capabilities/authentication.mdx
Labels: backport 0-20-0

#380 Docs: changes enterprise.md to index.md
  content/docs/capabilities/branding.md
  content/docs/capabilities/device-identity.mdx
  content/docs/capabilities/original-request-context.md
  content/docs/capabilities/ppl.mdx
  content/docs/internals/glossary.md
  content/docs/releases/enterprise/install/_category_.json
  content/docs/releases/enterprise/install/index.md
Labels: backport 0-20-0

#396 docs: update sidenav
  docusaurus.config.js
  src/components/docVersions.json
Labels: backport 0-20-0

#389 Docs: adds release notes for v21 console
  content/docs/releases/enterprise/upgrading.mdx
Labels: backport 0-21-0

#400 remove infinite redirect
  static/_redirects
Labels: backport 0-20-0, backport 0-21-0

#403 Update docusaurus to 2.3.1
  package.json
  yarn.lock
Labels: backport 0-21-0

#402 spellcheck
  content/docs/internals/data-storage.md
Labels: backport 0-21-0

#256 Docs: Adds new Enterprise Quickstart using Docker Compose
  content/docs/releases/enterprise/install/quickstart.mdx
  cspell.json
Labels: backport 0-20-0, backport 0-21-0

#409 fix k8s install string
  content/docs/deploying/k8s/install.md
Labels: backport 0-20-0, backport 0-21-0

#408 dont require signing_key generated as it's already in the docker-compose
  content/docs/releases/enterprise/install/quickstart.mdx
Labels: backport 0-21-0

#412 Docs: fixes Okta sections
  content/docs/identity-providers/okta.mdx
Labels: backport 0-20-0, backport 0-21-0

#415 Docs: updates JWT verification in relevant files
  content/docs/capabilities/getting-users-identity.md
  content/docs/capabilities/jwt-verification.mdx
  content/docs/guides/js-sdk.mdx
  content/docs/guides/jwt-verification.md
Labels: docs, backport 0-20-0, backport 0-21-0

#420 Docs: updates authz docs
  content/docs/capabilities/authorization.mdx
  content/docs/capabilities/img/authorization/apply-policies-to-routes.png
  content/docs/capabilities/img/authorization/enroll-device.png
  content/docs/capabilities/img/authorization/example-policy-editor.png
  content/docs/capabilities/img/authorization/example-policy-single-user.png
  content/docs/capabilities/img/authorization/ppl-editor-policy.png
  content/docs/capabilities/img/authorization/ppl-gui-policy.png
  content/docs/capabilities/img/authorization/ppl-rego-policy.png
Labels: backport 0-20-0, backport 0-21-0

#429 Docs: adds sso updates
  content/docs/capabilities/img/single-sign-out/sign-out-flow.svg
  content/docs/capabilities/single-sign-out.md
Labels: backport 0-20-0, backport 0-21-0

#430 move namespaces to capabilities
  content/docs/capabilities/authorization.mdx
  content/docs/capabilities/device-identity.mdx
  content/docs/capabilities/enterprise-api.mdx
  content/docs/capabilities/namespacing.mdx
  content/docs/concepts/policies.mdx
  content/docs/deploying/production-deployment.md
  content/docs/guides/istio.mdx
  content/docs/releases/enterprise/about.md
  content/docs/releases/enterprise/configure.md
  cspell.json
  sidebars.js
  static/_redirects
Labels: backport 0-21-0
