Repository pomerium/documentation, pull requests merged in 2023-03, with the labels that each got.

#441 [blocked] v0.21.x: bump core version in enterprise guide
  content/docs/releases/enterprise/install/kustomize.mdx
  k8s/config-template/ingress-console.yaml
  k8s/console/deployment/args.yaml
  k8s/console/deployment/image.yaml
  k8s/core/kustomization.yaml
Labels: blocked, backport 0-21-0

#437 update-k8s-reference-de5943be058323831de532a6fc74ae5be67b46fe
  content/docs/deploying/k8s/reference.md
Labels: backport 0-21-0

#440 Docs: updates encryption and certs docs
  content/docs/concepts/certificates.mdx
  content/docs/concepts/img/certificates/certificate-domain-challenge.png
  content/docs/concepts/img/certificates/certificate-wildcard-domain.png
  content/docs/concepts/img/certificates/certificates-ssl-report.png
  content/docs/concepts/img/certificates/certificates-valid-secure-certificate.png
  content/docs/concepts/img/certificates/security-headers.png
Labels: backport 0-20-0, backport 0-21-0

#453 Docs: fixes failed backport 440 to 0 20 0
  content/docs/concepts/certificates.mdx
  content/docs/concepts/img/certificates/certificate-domain-challenge.png
  content/docs/concepts/img/certificates/certificate-wildcard-domain.png
  content/docs/concepts/img/certificates/certificates-ssl-report.png
  content/docs/concepts/img/certificates/certificates-valid-secure-certificate.png
  content/docs/concepts/img/certificates/security-headers.png
Labels: docs

#457 Docs: adds guides index file
  content/docs/guides/index.md
  sidebars.js
Labels: backport 0-20-0, backport 0-21-0

#463 Update docusaurus.config.js
  docusaurus.config.js
Labels: docs, backport 0-21-0

#465 Docs: removes guides index.md file, adds slug to sidebars.js
  content/docs/guides/index.md
  sidebars.js
Labels: backport 0-20-0, backport 0-21-0

#462 Docs: cleans up redirects
  cspell.json
  static/_redirects
Labels: docs, 404, backport 0-21-0

#459 Adding Device Identity to this capabilities list
  content/docs/index.mdx
Labels: backport 0-20-0, backport 0-21-0

#476 Docs: adds enterprise installations page
  content/docs/releases/enterprise/install/installation.mdx
Labels: backport 0-20-0, backport 0-21-0

#486 Docs: fixes several 404s
  static/_redirects
Labels: docs, backport 0-20-0, docs/public, 404, backport 0-21-0

#501 Docs: fixes redirects
  static/_redirects
Labels: docs, docs/public, backport 0-21-0

#442 Docs: adds Jenkins guide
  content/docs/guides/img/jenkins/1-jenkins-admin-pass.png
  content/docs/guides/img/jenkins/10-matrix-auth.png
  content/docs/guides/img/jenkins/2-jenkins-dashboard.png
  content/docs/guides/img/jenkins/3-jenkins-sign-in.png
  content/docs/guides/img/jenkins/4-jwt-auth-plugin.png
  content/docs/guides/img/jenkins/5-jwt-form.png
  content/docs/guides/img/jenkins/6-enterprise-who-am-i.png
  content/docs/guides/img/jenkins/7-enterprise-jenkins-route.png
  content/docs/guides/img/jenkins/8-jenkins-email-policy.png
  content/docs/guides/img/jenkins/9-enterprise-jenkins-headers.png
  content/docs/guides/jenkins.mdx
  content/examples/jenkins/jenkins-docker-compose.md
Labels: backport 0-20-0, backport 0-21-0

#537 Docs: adds Envoy response details to troubleshooting
  content/docs/internals/troubleshooting.mdx
Labels: docs, backport 0-20-0, backport 0-21-0

#515 Docs: updates authenticate service url reference in GUI Config
  content/docs/releases/enterprise/configure.md
Labels: docs, backport 0-21-0

#544 Docs: updates signing key gui config
  content/docs/releases/enterprise/configure.md
Labels: docs, backport 0-21-0

#546 Docs: updates client-side mtls doc
  content/docs/capabilities/mtls-clients.mdx
Labels: docs, backport 0-21-0

#554 Docs: updates mtls services guide
  content/_install-mkcert.md
  content/docs/capabilities/mtls-services.mdx
Labels: docs, backport 0-21-0

#558 Docs: fixes load balancing link issue
  content/docs/reference/routes/health-checks.md
Labels: docs, backport 0-21-0

#560 Update autocert-directory.md
  content/docs/reference/autocert/autocert-directory.md
Labels: backport 0-21-0

#562 Docs: adds v21 changelogs
  content/docs/releases/changelog.mdx
Labels: docs, backport 0-21-0

#564 Docs: adds console changelogs
  content/docs/releases/enterprise/changelog.mdx
Labels: docs, backport 0-21-0
