Repository pomerium/documentation, pull requests merged in 2024-09, with the labels that each got.

#1566 Updates self-hosted authn doc
  content/docs/capabilities/hosted-authenticate-service.md
  content/docs/capabilities/self-hosted-authenticate-service.md
  content/docs/identity-providers/index.mdx
Labels: backport 0-26-0

#1597 Adds v0.27 to archived versions
  src/components/docVersions.json
Labels: backport 0-27-0

#1591 update databroker settings reference page
  content/docs/reference/databroker.mdx
  content/docs/reference/reference.json
  static/_redirects
Labels: backport 0-27-0

#1602 Updates version tags to v0.27.0
  content/docs/concepts/clusters.mdx
  content/docs/core.mdx
  content/docs/courses/fundamentals/zero-advanced-routes.mdx
  content/docs/courses/fundamentals/zero-build-routes.mdx
  content/docs/courses/fundamentals/zero-single-sign-on.mdx
  content/docs/enterprise/install.mdx
  content/docs/k8s/install.md
  content/docs/k8s/quickstart.mdx
  content/docs/quickstart.mdx
  content/docs/zero/install.mdx
  content/examples/enterprise/hosted-auth-docker.yaml.md
  k8s/console/deployment/image.yaml
  k8s/core/kustomization.yaml
Labels: backport 0-27-0

#1607 Adds correct Zero Courses link
  content/docs/quickstart.mdx
Labels: backport 0-26-0, backport 0-27-0

#1611 Adds a pushfeedback widget
  cspell.json
  docusaurus.config.js
  package.json
  yarn.lock
Labels: backport 0-27-0

#1622 k8s: set release to v0.27.1
  content/docs/concepts/clusters.mdx
  content/docs/core.mdx
  content/docs/courses/fundamentals/zero-advanced-routes.mdx
  content/docs/courses/fundamentals/zero-build-routes.mdx
  content/docs/courses/fundamentals/zero-single-sign-on.mdx
  content/docs/guides/code-server.mdx
  content/docs/k8s/install.md
  content/docs/k8s/quickstart.mdx
  content/docs/quickstart.mdx
  content/docs/zero/install.mdx
  content/examples/enterprise/hosted-auth-docker.yaml.md
  k8s/console/deployment/image.yaml
  k8s/core/kustomization.yaml
Labels: backport 0-27-0
