Repository pomerium/documentation, pull requests merged in 2024-05, with the labels that each got.

#1385 Updates ppl example
  content/docs/capabilities/ppl.mdx
Labels: backport 0-25-0

#1391 docs(data-storage): remove mention of encryption with deprecated Redis backend
  content/docs/internals/data-storage.md
Labels: backport 0-24-0, backport 0-25-0

#1405 build(deps): update @babel/types and @mui/x-data-grid
  package.json
  yarn.lock
Labels: backport 0-19-0, backport 0-18-0

#1407 FIX: use correct config key for cookie expiration
  content/docs/reference/cookies.mdx
Labels: backport 0-22-0, backport 0-23-0, backport 0-24-0

#1419 Updates archived versions for v0.26
  src/components/docVersions.json
Labels: backport 0-26-0

#1427 Adds v0.26 core upgrade guide
  content/docs/deploy/core/upgrading.mdx
Labels: backport 0-26-0

#1429 update runtime flags reference page
  content/docs/reference/routes/from.mdx
  content/docs/reference/runtime-flags.md
Labels: backport 0-26-0

#1435 glossary: fix some broken link syntax
  content/docs/internals/glossary.md
Labels: backport 0-26-0
