Repository pomerium/documentation, pull requests merged in 2024-01, with the labels that each got.

#1024 Docs: updates footer ns color
  src/components/Newsletter.js
  src/css/custom.css
Labels: backport 0-24-0

#1132 Docs: code server update
  content/docs/guides/code-server.mdx
  content/docs/guides/img/code-server/code-server-build-route.png
  content/docs/guides/img/code-server/code-server-password-prompt.png
  content/docs/guides/img/code-server/vscode-helloworld.png
  content/docs/guides/img/code-server/vscode-pomerium.png
Labels: docs, backport 0-24-0

#1141 Docs: Case sensitive string notice for Enterprise Console
  content/docs/deploy/enterprise/configure.mdx
  content/docs/internals/troubleshooting.mdx
Labels: backport 0-24-0

#1145 Docs: rewrites wildcard processing order example
  content/docs/reference/routes/from.mdx
Labels: backport 0-22-0, backport 0-23-0, backport 0-24-0

#1152 Docs: updates img and example text
  content/docs/capabilities/authorization.mdx
  content/docs/capabilities/img/authorization/ppl-edit-policy.png
  content/docs/capabilities/img/authorization/ppl-editor-policy.png
  content/docs/deploy/k8s/reference.md
  src/components/Newsletter.js
Labels: backport 0-21-0, backport 0-22-0, backport 0-23-0, backport 0-24-0

#1151 Docs: adds core v0.25 changelog
  content/docs/deploy/core/changelog.mdx
Labels: backport 0-25-0

#1156 Docs: adds core upgrade guide
  content/docs/deploy/core/upgrading.mdx
Labels: backport 0-25-0

#1158 Docs: updates archived versions
  src/components/docVersions.json
Labels: backport 0-25-0

#1157 Docs: adds console upgrade guide
  content/docs/deploy/enterprise/upgrading.mdx
Labels: backport 0-25-0

#1137 Docs: adds v0.25.0 Console changelog callouts
  content/docs/deploy/enterprise/changelog.mdx
Labels: backport 0-25-0

#1169 Docs: fixes console formatting
  content/docs/deploy/enterprise/upgrading.mdx
Labels: backport 0-25-0

#1172 Docs: removes cookie secure example from Enterprise tab
  content/docs/reference/cookies.mdx
Labels: backport 0-25-0

#1154 Docs: groups ppl criterion
  content/docs/capabilities/ppl.mdx
Labels: backport 0-22-0, backport 0-23-0, backport 0-24-0, backport 0-25-0

#1180 Fundamentals / JWT Verification page: fix links
  content/docs/courses/fundamentals/jwt-verification.md
Labels: backport 0-24-0, backport 0-25-0

#1184 update mermaid diagram configuration
  docusaurus.config.js
  package.json
  yarn.lock
Labels: backport 0-25-0

#1188 Docs: adds v0.25 tags
  content/docs/deploy/enterprise/install.mdx
  content/examples/enterprise/hosted-auth-docker.yaml.md
Labels: backport 0-25-0

#1189 Docs: fixes pass id headers redirect
  static/_redirects
Labels: backport 0-25-0

#1192 reference.json: update Autocert link paths
  content/docs/reference/reference.json
Labels: backport 0-25-0

#1201 Docs: separate global timeouts
  content/docs/reference/global-timeouts.mdx
  content/docs/reference/reference.json
Labels: backport 0-25-0

#1203 Docs: fixes timeouts formatting
  content/docs/reference/global-timeouts.mdx
Labels: backport 0-25-0

#1206 Docs: updates route-level idle timeout ID
  content/docs/reference/reference.json
Labels: backport 0-25-0

#1209 Docs: adds console changelog
  content/docs/deploy/enterprise/changelog.mdx
Labels: backport 0-25-0

#1208 Docs: adds robots.txt notice
  content/docs/reference/routes/public-access.mdx
Labels: backport 0-25-0

#1198 Docs: add enterprise admonition
  content/docs/capabilities/branding.md
  content/docs/capabilities/original-request-context.md
  docusaurus.config.js
  src/theme/Admonition/Types.js
  src/theme/Admonition/styles.module.css
Labels: backport 0-25-0
