Repository pomerium/documentation, pull requests merged in 2025-03, with the labels that each got.

#1797 rewrite all-in-one vs split-service
  content/docs/internals/configuration.mdx
Labels: backport 0-28-0

#1803 OPE-117 add _headers to not index
  _headers
  cspell.json
Labels: backport 0-20-0, backport 0-21-0, backport 0-22-0, backport 0-23-0, backport 0-24-0, backport 0-25-0, backport 0-19-0, backport 0-18-0, backport 0-26-0, backport 0-27-0

#1819 move _headers file to static/
  static/_headers
Labels: backport 0-24-0, backport 0-25-0, backport 0-26-0

#1826 bearer-token-format: remove notes about additional headers
  content/docs/reference/bearer-token-format.mdx
Labels: backport 0-29-0

#1824 docs: Add documentation for special /.pomerium routes
  content/docs/internals/special-routes.md
  cspell.json
Labels: backport 0-28-0, backport 0-29-0

#1836 Fix Terraform HCL code formatting
  docusaurus.config.js
Labels: backport 0-29-0

#1841 Fix version tag references that were missed
  content/docs/deploy/k8s/install.md
  content/docs/deploy/k8s/quickstart.mdx
  content/examples/enterprise/hosted-auth-docker.yaml.md
  k8s/console/deployment/image.yaml
  k8s/core/kustomization.yaml
Labels: backport 0-29-0

#1843 Cover Direct IdP Authentication in our Capabilites
  content/docs/capabilities/authentication.mdx
Labels: backport 0-29-0
