Repository pomerium/documentation, pull requests merged in 2025-01, with the labels that each got.

#1748 Fix sidebar capitalization and typo
  content/docs/capabilities/getting-users-identity.mdx
  content/docs/deploy/cloud/_category_.json
Labels: backport 0-28-0

#1751 docs: improved self-managed Docker documentation example
  content/docs/deploy/core.mdx
Labels: Fix Content, backport 0-28-0

#1755 chore: update _redirects to match new sitemap (27 vs 28) and reorganized docs
  static/_redirects
Labels: 404, backport 0-28-0

#1757 chore: update redirects to add anchors
  static/_redirects
Labels: 404, backport 0-28-0

#1767 chore: add additional 404 redirects for missing documentation pages
  static/_redirects
Labels: 404, backport 0-28-0
